GET http://localhost:3000/api/v1/users/authentication-tokens
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOm51bGwsInVzZXJuYW1lIjoic3RldmVmIiwiZW1haWwiOiJzZmVkZGVzQG91dGxvb2suY29tIiwiaWF0IjoxNzA0NDA2MTk0LCJleHAiOjE3MDQ0MTMzOTR9.kRA2Wh8FC6qVmVjGIlQWwZF8jFiN9mskLtNNtv8bbCM